steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Run performance tests
    uses: swissspidy/wp-performance-action@v1
    with:
      plugins: |
        ./wp-custom-css-body-class
      urls: |
        /
        /sample-page/