name: Performance Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  performance-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run performance tests
        uses: swissspidy/wp-performance-action@main
        with:
          plugins: |
            ./wp-custom-css-body-class
          urls: |
            /
            /sample-page/
      - name: 'Echo results path'
        run: echo ${{steps.performance-tests.outputs.results}}